### ISSUE TITLE
BCM943602CS

### ISSUE THREAD

**Issue by yanyingjie007** [gazzmanzx6/OC_Dell_Latitude_7370#1]
hi gazzmanzx6

just have a question that how can you insert BCM943602CS with adapter inside the slim body of 7370? 

I think there is no enough space to do so

**Comment by gazzmanzx6** [comment]
It uses a ribbon cable between the motherboard connector and the BCM943602CS. This enable the card to be located under the edge of the battery. Not ideal and it is very tight but it does the job.

**Comment by yanyingjie007** [comment]
thanks very much for your explanation
