### ISSUE TITLE
OC Grabbed Zerro System-ID

### ISSUE THREAD

**Issue by sojab0on** [gazzmanzx6/OC_Dell_Latitude_7370#11]
Hi i tried you OC for my 7370 but it is halting on critical error 
OC: Grabbed zero system0id of SB, this is not allowed

**Comment by gazzmanzx6** [comment]
Hi, try setting "SecureBootModel" to Disabled

**Comment by sojab0on** [comment]
That made it past teh error but it hangs on the Apple logo now
I used a clean mojave img but gues the diffrence between big sur and moajve can make this happen

**Comment by gazzmanzx6** [comment]
Have you made sure you have followed the instructions on BIOS settings?
BIOS setting:

> System Configuration > Thunderbolt Adapter Configuration
> Security level - No Security
> Virtualization Support > VT for Direct I/O
> Enabled (Now required for Thunderbolt to work in Big Sur)
> BIOS tweaks:
> 
> disable CFG Lock: ~~setup_var 0x109 0x0 Verify before use (extracted from BIOS 1.19.5)~~
> Use CFGLock tool to find and toggle value
> increase DVMT: setup_var 0x432 0x3 Verify before use (extracted from BIOS 1.27.3)

**Comment by sojab0on** [comment]
the DVMT stuff i did 
 vt directed io was already on 
 saw the thunderbolt wasent set to no security no it is but still hangs at apple logo
i cant seen to get the boot arch -v to work to see why

**Comment by gazzmanzx6** [comment]
I suspect it may just be that the newer OS won't work.

**Comment by sojab0on** [comment]
okay 
i will backup the efi and remake a installer but saw your config is for monterey not big sur or earlier
