### ISSUE TITLE
No headphone audio

### ISSUE THREAD

**Issue by apodacaduron** [gazzmanzx6/OC_Dell_Latitude_7370#2]
Hi good morning, I have the same laptop just with 8gb instead of 16gb and default Wifi card, the only thing I've been having issues is trying to make headphone jack work, it just makes a low volume constant noise, I'm not sure if you could give me some tips, it uses ALC256 as well, should I just try all layout id possible?

**Comment by gazzmanzx6** [comment]
Have you installed ComboJack?
https://github.com/hackintosh-stuff/ComboJack

That is what fixed it for me.

**Comment by apodacaduron** [comment]
Thank you, worked out fine
