### ISSUE TITLE
Boot stuck on apple logo

### ISSUE THREAD

**Issue by modern3** [gazzmanzx6/OC_Dell_Latitude_7370#3]
Hi, I have the same laptop(M7/16GB/512Gb), i try to install BigSur(hackintosh-shop) with your EFI, but but the first launch stuck on apple logo or or shows a link to restore
Please add link to the system image
thanks

**Comment by gazzmanzx6** [comment]
I don’t support hackintosh-shop. This works with Big Sur from Apple.
