### ISSUE TITLE
Would this work on my hardware?

### ISSUE THREAD

**Issue by mx4address** [gazzmanzx6/OC_Dell_Latitude_7370#4]
My Latitude 7370 is pretty different.
It's the same m7-6Y75, but with 8 gigs of ram.
The audio is: Intel Skylake-U/Y PCH - High Definition Audio (unsure about this.)
The network is: Intel Dual Band Wireless-AC 8260 (a/b/g/n = Wi-Fi 4/ac = Wi-Fi 5), Bluetooth 4.2
It also has only 256 GB storage of NVME
And I'm pretty unsure about my BIOS. (it is in repair sadly, cuz of overheating issue)

**Comment by gazzmanzx6** [comment]
It will probably work except for the Wi-Fi and Bluetooth.
There is an Intel driver out there but I have no idea if it would work.

**Comment by mx4address** [comment]
Me neither. And I don't rlly need Bluetooth, so Bluetooth isn't necessary.
Although I also found this. https://github.com/OpenIntelWireless/itlwm

**Comment by gazzmanzx6** [comment]
That one has been replaced by this. https://github.com/OpenIntelWireless/itlwm

**Comment by mx4address** [comment]
> 
> 
> That one has been replaced by this. https://github.com/OpenIntelWireless/itlwm

I know, I saw that and I replaced the text.

**Comment by mx4address** [comment]
not kext, the text i wrote here

**Comment by mx4address** [comment]
and also, if i wanna install mac os, i think it needs internet idk to install and that would be a problem cuz i have no ethernet things

**Comment by gazzmanzx6** [comment]
You can make a usb flash drive installer so no internet connection would be required for the install.

**Comment by mx4address** [comment]
oh. so like i do it through the normal way of making the usb or is it something else?

**Comment by gazzmanzx6** [comment]
Normal way the same as a real Mac. If you create the EFI on the same usb drive you can boot and install from the same drive.

**Comment by mx4address** [comment]
the only thing is, i have no mac. so that wouldn't be possible

**Comment by mx4address** [comment]
maybe in a vm i could do so, but it'll take up a whole ton of space

**Comment by gazzmanzx6** [comment]
There are ways of creating it on a PC I think but I haven't tried it.

**Comment by mx4address** [comment]
like with transmac for example? idk if it works but i thought about it

**Comment by gazzmanzx6** [comment]
https://manjaro.site/how-to-create-macos-usb-installation-disk-from-windows-10/

gibMacOS seems to be quite a common way of creating it.
Again I have never tried it as I have a real Mac.

**Comment by mx4address** [comment]
it looks suspicious as the mac os stuff doesn't weight much. unsure about this i have a screenshot. 
![immagine](https://user-images.githubusercontent.com/84406344/136709815-ec9d108f-2ed8-4490-913f-a89dce24b4ad.png)

**Comment by gazzmanzx6** [comment]
That's just the recovery part not the installer.

**Comment by mx4address** [comment]
so welp that ain't the installer so that won't be working idk.

**Comment by mx4address** [comment]
and also, should i choose itlwm.kext or AirportItlwm.kext

**Comment by gazzmanzx6** [comment]
Can't help with that as I have never used it.
