### ISSUE TITLE
Booting issue

### ISSUE THREAD

**Issue by mx4address** [gazzmanzx6/OC_Dell_Latitude_7370#5]
I booted on my configuration, and it would show a weird text based OpenCore menu, then when I booted Mac OS, it would show the Apple logo but then it gets stuck on it and won't work

**Comment by mx4address** [comment]
This is how I did it.
![image](https://user-images.githubusercontent.com/84406344/137738663-6f2a63c8-4a47-4c33-b509-bcdc04b490fa.png)

**Comment by gazzmanzx6** [comment]
I think you need to read up on how to do this. There are plenty of sites telling you how to create the USB boot disk.

What you have done is not correct.
The files from this repo need to be in the EFI partition not the main partition.
