### ISSUE TITLE
It won't pass booting screen installing monterey with error iog flags 0x3 

### ISSUE THREAD

**Issue by EhshanAmin** [gazzmanzx6/OC_Dell_Latitude_7370#6]
It has the same BIOS version 1.27.3
With m5 cpu 8gb ram
And Intel wifi card
Without wwan card and touch display
1080p resolution

Tried cfg lock tool with no luck.
Can you please help me ...
I am new in hackintosh world...

**Comment by gazzmanzx6** [comment]
Have you set the DVMT?
The Intel Wi-Fi won't work with this EFI.

**Comment by EhshanAmin** [comment]
Sir as I said I am new in hackintosh... Can you please guide?
How to set dvmt...
In bios it is set to 128mb

**Comment by gazzmanzx6** [comment]
See points 5 to 7 on this page: [https://osxlatitude.com/forums/topic/13963-changing-dvmt-values-in-bios/](https://osxlatitude.com/forums/topic/13963-changing-dvmt-values-in-bios/)

Be warned if you do this wrong it could brick your laptop.

**Comment by EhshanAmin** [comment]
This part I have done. But nothing happened.

**Comment by gazzmanzx6** [comment]
iog flags 0x3 is a graphics error so it seems like it is not working.

**Comment by EhshanAmin** [comment]
How can I solve it. If it's graphics error.
And boot arg is left empty.

**Comment by gazzmanzx6** [comment]
By making sure the DVMT is set correctly.

**Comment by EhshanAmin** [comment]
Ok I'll give it another try and will update you...

**Comment by EhshanAmin** [comment]
After changing DVMT value I just passed through boot screen.
But while installing monterey it hangs my laptop. And wot move forward.
I tried it from start 2-3 times but it sticks mostly while copying files from usb...
Can you suggest any advice...

**Comment by EhshanAmin** [comment]
After changing DVMT value I just passed through boot screen.
But while installing monterey it hangs my laptop. And wot move forward.
I tried it from start 2-3 times but it sticks mostly while copying files from usb...
Can you suggest any advice...

Also it take long to boot until Dell logo appears.

**Comment by EhshanAmin** [comment]
One more thing is when I close lid and open lid again there is only blank black screen no login screen. And there is no response if i tap the on/off key. Then I shut it illegally...
Else everything is working flawlessly...

**Comment by EhshanAmin** [comment]
Now my laptop won't even start only caps lock blink... Sometimes it startup but mostly caps lock blink...

**Comment by gazzmanzx6** [comment]
As previously warned, **doing this may brick your laptop.**
I suggest you try to reset it and leave it with Windows installed.

**Comment by EhshanAmin** [comment]
It can't even start properly
I also tried to update bios but no luck... 
Is there a way out of this.

**Comment by EhshanAmin** [comment]
When turning on led on power key blinks so many times.
And somehow it starts after long time... 
When I try to flash bios update which requires a restart but bios won't restart it crashes...

**Comment by gazzmanzx6** [comment]
I have no idea. I haven't had this problem. Maybe a clip on programmer on the BIOS chip but that would possibly require taking the laptop apart.
