### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by JackHe98** [gazzmanzx6/OC_Dell_Latitude_7370#8]
Hi. I use your EFI, the same laptop as you, but my screen is 3200x1800. I encountered two problems, the first one, when my laptop is plugged in and unplugged, it will crash directly. Second, my laptop trackpad can be used, but the settings prompt "Trackpad not found". Could you please help me with these two issues?

**Comment by gazzmanzx6** [comment]
No idea about the crash. Mine does not do that.
As for the trackpad, that is normal as the trackpad shows as a mouse due to driver limitations.

**Comment by JackHe98** [comment]
I've asked a lot of people who don't understand this and I don't know what's wrong. Do you have any advice on this issue please? I don't even know where to start, I don't know how to fix it.
